title:              Lupin's Blog
email:              lupin.devv@gmail.com
description:        
author:             Lupin
baseurl:            "/devlupin.github.io"
url:                "https://devlupin.github.io"

# Social Profiles
github_username:    devLupin

# Add your google-analytics ID here to activate google analytics
google_analytics:    # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
