title:              Lupin's Blog
email:              lupin.devv@gmail.com
description:        
author:             Lupin
baseurl:            "/devlupin.github.io"
url:                "https://devlupin.github.io"

# Social Profiles
twitter_username:   
github_username:    devLupin
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:    # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
